spring.mail.password: mailpassword

jhipster:
  security.authentication.jwt.base64-secret: MzNkNDYyZDgyZWI0MTJiMGNlNmI1MzIxNThiMzkyNTQ3OTY4ZTA4ZDM3OThlNDE2ZGQzYzc4N2UwZmRhMDA3NGJjZmJlZjZjYjExYWQxZmU1M2NjN2QwZTM3MTYyOWRjYmM2MGM4NmFlYWZkODI3ODNhNjlhNGMyMDljZWJiMWU=
  cors:
    allowed-origins: 'https://www.my.staging.farue.rwth-aachen.de'
    allowed-methods: '*'
    allowed-headers: '*'
    exposed-headers: 'Authorization,Link,X-Total-Count,X-${jhipster.clientApp.name}-alert,X-${jhipster.clientApp.name}-error,X-${jhipster.clientApp.name}-params'
    allow-credentials: true
    max-age: 1800
