version: '2'
services:
  autocut-app:
    image: "registry.git.rwth-aachen.de/farue/autocut"
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:mysql://autocut-mysql:3306/autocut?useUnicode=true&characterEncoding=utf8&useSSL=false
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 8080:8080
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.autocut-r1.rule=Host(`www.farue.rwth-aachen.de`)"
      - "traefik.http.routers.autocut-r1.entrypoints=web"
      - "traefik.http.services.autocut-s1.loadbalancer.server.port=8080"
  autocut-mysql:
    extends:
      file: mysql.yml
      service: autocut-mysql
