version: '3.8'

networks:
  traefik:
    external: true
  autocut:

volumes:
  autocut-db:

services:
  autocut-app:
    image: 'registry.git.rwth-aachen.de/farue/autocut'
    container_name: 'autocut-app'
    restart: always
    networks:
      - traefik
      - autocut
    environment:
      - TZ=Europe/Berlin
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,api-docs
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:mysql://autocut-mysql:3306/autocut?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC&createDatabaseIfNotExist=true
      - SPRING_LIQUIBASE_URL=jdbc:mysql://autocut-mysql:3306/autocut?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC&createDatabaseIfNotExist=true
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
      - JASYPT_ENCRYPTOR_PASSWORD
    ports:
      - 8080:8080
    labels:
      - 'traefik.enable=true'
      # www redirect
      - 'traefik.http.middlewares.www-redirect.redirectregex.regex=^(https?)://farue.rwth-aachen.de(.*)'
      - 'traefik.http.middlewares.www-redirect.redirectregex.replacement=$${1}://www.farue.rwth-aachen.de$${2}'
      - 'traefik.http.middlewares.www-redirect.redirectregex.permanent=true'
      # http route
      - 'traefik.http.routers.autocut-http.rule=Host(`farue.rwth-aachen.de`, `www.farue.rwth-aachen.de`)'
      - 'traefik.http.routers.autocut-http.entrypoints=web'
      - 'traefik.http.middlewares.https-redirect.redirectscheme.scheme=https'
      - 'traefik.http.middlewares.https-redirect.redirectscheme.permanent=true'
      - 'traefik.http.routers.autocut-http.middlewares=www-redirect@docker, https-redirect@docker'
      - 'traefik.http.routers.autocut-http.service=autocut-service'
      # https route
      - 'traefik.http.routers.autocut-https.rule=Host(`farue.rwth-aachen.de`, `www.farue.rwth-aachen.de`)'
      - 'traefik.http.routers.autocut-https.entrypoints=websecure'
      - 'traefik.http.routers.autocut-https.tls=true'
      - 'traefik.http.routers.autocut-https.tls.certresolver=le'
      - 'traefik.http.routers.autocut-https.middlewares=www-redirect@docker'
      - 'traefik.http.routers.autocut-https.service=autocut-service'
      # autocut service
      - 'traefik.http.services.autocut-service.loadbalancer.server.port=8080'
    healthcheck:
      test: curl --fail -s localhost:8080/management/health 2>&1 | grep UP || exit 1
      interval: 20s
      timeout: 5s
      retries: 5
      start_period: 40s

  autocut-mysql:
    image: mysql:8.0.26
    container_name: 'autocut-mysql'
    restart: always
    volumes:
      - autocut-db:/var/lib/mysql/
    networks:
      - autocut
    environment:
      - TZ=Europe/Berlin
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=autocut
    ports:
      - 127.0.0.1:3306:3306
    command: mysqld --lower_case_table_names=1 --skip-ssl --character_set_server=utf8mb4 --explicit_defaults_for_timestamp
    healthcheck:
      test: mysqladmin ping -h localhost
      timeout: 20s
      retries: 10

  autocut-backup:
    image: tiredofit/db-backup
    container_name: autocut-backup
    restart: always
    volumes:
      - /var/lib/restic/backup/autocut/db:/backup
    networks:
      - autocut
    environment:
      TZ: Europe/Berlin
      DB_TYPE: mysql
      DB_HOST: autocut-mysql
      DB_NAME: autocut
      DB_USER: root
      DB_DUMP_FREQ: 360 # in minutes, so every 6 hours
      DB_DUMP_BEGIN: +5
      DB_CLEANUP_TIME: 360
      SPLIT_DB: 'TRUE'
      MD5: 'FALSE'
