version: '2'

networks:
  traefik:
    external: true

services:
  autocut-mysql:
    image: mysql:8.0.20
    volumes:
      - ~/volumes/autocut/mysql/:/var/lib/mysql/
    networks:
      - 'traefik'
    environment:
      - MYSQL_USER=root
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=autocut
    ports:
      - 3306:3306
    command: mysqld --lower_case_table_names=1 --skip-ssl --character_set_server=utf8mb4 --explicit_defaults_for_timestamp
